[[plugins]]
  package = "netlify-plugin-python"
  [plugins.inputs]
    python_version = "3.10"
    requirements = "source/requirements.txt"

[build]
  command = "bash ./build.sh"
  publish = "_build/html"
